name: Pylint

on: 
  push:
    paths-ignore: 
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - '_backup/**'
      - 'migrations/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_pylint.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        # pylint `ls -R|grep .py$|xargs`
        pylint --fail-under=5 --load-plugins pylint_flask_sqlalchemy,pylint_flask,pylint_sqlalchemy **/*.py
